/*
 * Subscription Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	"subscriptionManager/db"
	sw "subscriptionManager/go"
)

func main() {
	db.Init()
	log.Printf("Server started")
	// Initialize security layer
	if err := sw.InitAuthenticator(); err != nil {
		log.Fatal("Failed to initialize security. Exiting...")
		return
	}

	router := sw.NewRouter()

	log.Fatal(router.Run(":8085"))
}
