/*
 * Subscription Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package subscriptionManager

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// HealthGet -
func HealthGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
