/*
 * Subscription Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package subscriptionManager

import (
	"net/http"

	"subscriptionManager/db"
	"subscriptionManager/models"

	"github.com/gin-gonic/gin"
)

// PlansGet - Returns a list of available subscription plans.\"

func PlansGet(c *gin.Context) {
	var plans []models.AvailablePlans
	db.DB.Find(&plans)
	c.JSON(http.StatusOK, gin.H{"plans": plans})
}
