/*
 * Subscription Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package subscriptionManager

type APayment struct {

	IssuedDate string `json:"issuedDate,omitempty"`

	Amount float32 `json:"amount,omitempty"`

	Currency string `json:"currency,omitempty"`

	Method string `json:"method,omitempty"`
}
